// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrWopFpMEAcArRg4nhBsF1yv54-HCEFI',
    appId: '1:755472825710:web:172d0aab1c508a091b557f',
    messagingSenderId: '755472825710',
    projectId: 'togoride-app-d8e89',
    authDomain: 'togoride-app-d8e89.firebaseapp.com',
    databaseURL: 'https://togoride-app-d8e89-default-rtdb.firebaseio.com',
    storageBucket: 'togoride-app-d8e89.appspot.com',
    measurementId: 'G-EHCMQ54B7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz6kVILoHJmepM0jqT1d_ivnogDUdGc4g',
    appId: '1:755472825710:android:513ce73626dea0461b557f',
    messagingSenderId: '755472825710',
    projectId: 'togoride-app-d8e89',
    databaseURL: 'https://togoride-app-d8e89-default-rtdb.firebaseio.com',
    storageBucket: 'togoride-app-d8e89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC25RLbS1yHsLjncM9lo__8LQWMFMq_Igg',
    appId: '1:755472825710:ios:27c0cf54dc997ae31b557f',
    messagingSenderId: '755472825710',
    projectId: 'togoride-app-d8e89',
    databaseURL: 'https://togoride-app-d8e89-default-rtdb.firebaseio.com',
    storageBucket: 'togoride-app-d8e89.appspot.com',
    iosBundleId: 'com.example.togorideUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC25RLbS1yHsLjncM9lo__8LQWMFMq_Igg',
    appId: '1:755472825710:ios:cd2ab636ff69c3af1b557f',
    messagingSenderId: '755472825710',
    projectId: 'togoride-app-d8e89',
    databaseURL: 'https://togoride-app-d8e89-default-rtdb.firebaseio.com',
    storageBucket: 'togoride-app-d8e89.appspot.com',
    iosBundleId: 'com.example.togorideUser.RunnerTests',
  );
}
